# Jobs defined here use the idp/ci docker image from ECR by default. 
# Images are built via the identity-devops GitLab pipeline.

variables:
  BUNDLER_VERSION: "2.3.13"
  ECR_REGISTRY: '${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com'
  IDP_WORKER_IMAGE_TAG: 'main'
  IDP_IMAGE_TAG: 'main'
  PKI_IMAGE_TAG: 'main'

default:
  image: '${ECR_REGISTRY}/dashboard/ci:latest'

before_script:
  - gem install bundler --version $BUNDLER_VERSION

.bundle_install: &bundle_install
  - bundle check || bundle install --retry=3  --path vendor/bundle

 
.build_cache:
  - &ruby_cache
    key:
      files:
        - Gemfile.lock
    paths:
      - vendor/bundle
    policy: pull
 

stages:
  - .pre
  - test
  - deploy


install_dependencies:
  stage: .pre
  variables:
  cache:
    - <<: *ruby_cache
      policy: pull-push

  script:
    - *bundle_install
 #   - bundle exec rake login:deploy_json

test_release:
  stage: test
  needs:
    - job: install_dependencies
  cache:
    - <<: *ruby_cache
  script:
    - *bundle_install
    - make test
  artifacts:
    paths:
      - /tmp/test-results
