# Jobs defined here use the idp/ci docker image from ECR by default. 
# Images are built via the identity-devops GitLab pipeline.

variables:
  BUNDLER_VERSION: "2.3.13"
  ECR_REGISTRY: '${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com'
  IDP_WORKER_IMAGE_TAG: 'main'
  IDP_IMAGE_TAG: 'main'
  PKI_IMAGE_TAG: 'main'

workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" || $CI_PIPELINE_SOURCE == "external_pull_request_event" || $CI_PIPELINE_SOURCE == "web"'
    - if: '$CI_COMMIT_BRANCH == "main"'
    - if: $CI_COMMIT_TAG
      when: never


default:
  image: '${ECR_REGISTRY}/dashboard/ci:latest'

before_script:
  - gem install bundler --version $BUNDLER_VERSION

.bundle_install: &bundle_install
  - bundle check || bundle install --retry=3  --path vendor/bundle

 
.build_cache:
  - &ruby_cache
    key:
      files:
        - Gemfile.lock
    paths:
      - vendor/bundle
    policy: pull
 

stages:
  - .pre
  - test
  - deploy


install_dependencies:
  stage: .pre
  variables:
  cache:
    - <<: *ruby_cache
      policy: pull-push

  script:
    - *bundle_install
 #   - bundle exec rake login:deploy_json

test_release:
  stage: test
  needs:
    - job: install_dependencies
  cache:
    - <<: *ruby_cache
  script:
    - *bundle_install
    - make test


deploy_to_cloudgov:
  only:
  - main
  stage: deploy
  image: '${ECR_REGISTRY}/dashboard/ci:latest'
  script:
    - curl  -v -L -o cf8-cli_linux_x86-64.tgz "https://packages.cloudfoundry.org/stable?release=linux64-binary&version=v8&source=github" 
    - tar -xvzf cf8-cli_linux_x86-64.tgz
    - mv cf8 /usr/local/bin
    - cf8 --version
    - curl -o /usr/share/bash-completion/completions/cf8 https://raw.githubusercontent.com/cloudfoundry/cli-ci/master/ci/installers/completion/cf8
    - *bundle_install
    - bundle exec rake login:deploy_json
    -  bundle config set cache_all true
    - bundle package
    - cf8 login -a https://api.fr.cloud.gov -u "e1fdd211-f191-40e8-99c7-4e7164d9ae76" -p $CF8_PASS -o "gsa-login-prototyping" -s "$SPACE"
    - cf8 push identity-fake-server -b ruby_buildpack -s cflinuxfs4
  parallel:
    matrix:
      - SPACE: [pt]
