---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fake-server
  labels:
    app: fake-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fake-server
  template:
    metadata:
      labels:
        app: fake-server
    spec:
      containers:
      - name: fake-server
        image: logindotgov/identity-fake-server:latest
        ports:
        - containerPort: 5555

---
apiVersion: v1
kind: Service
metadata:
  name: fake-server
spec:
  ports:
    - port: 5555
      targetPort: 5555
      protocol: TCP
  type: NodePort
  selector:
    app: fake-server

# ---
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: fake-server
#   annotations:
#     alb.ingress.kubernetes.io/scheme: internet-facing
#     alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}]'
# spec:
#   ingressClassName: alb
#   tls:
#   - hosts:
#     - fake-server.identitysandbox.gov
#   rules:
#     - http:
#         paths:
#           - path: /
#             pathType: Prefix
#             backend:
#               service:
#                 name: fake-server
#                 port:
#                   number: 5555

