---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fake-server
  labels:
    app: fake-server
spec:
  selector:
    matchLabels:
      app: fake-server
  template:
    metadata:
      labels:
        app: fake-server
    spec:
      containers:
      - name: fake-server
        image: logindotgov/identity-fake-server:latest
        resources:
          requests:
            cpu: "250m"
            memory: "128Mi"
          limits:
            cpu: "800m"
            memory: "1024Mi"
        ports:
        - containerPort: 5555

---
apiVersion: v1
kind: Service
metadata:
  name: fake-server
spec:
  ports:
    - port: 5555
      targetPort: 5555
      protocol: TCP
  type: NodePort
  selector:
    app: fake-server

---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: fake-server
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: fake-server
  minReplicas: 1
  maxReplicas: 100
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fake-server
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}]'
    external-dns.alpha.kubernetes.io/hostname: fake-server.loadtest.identitysandbox.gov
spec:
  ingressClassName: alb
  tls:
  - hosts:
    - fake-server.loadtest.identitysandbox.gov
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: fake-server
                port:
                  number: 5555
