PORT ?= 5555
PUMA_MIN_THREADS ?= 8
PUMA_MAX_THREADS ?= 32
PUMA_NUM_WORKERS ?= 3

run:
	PORT=$(PORT) \
	PUMA_MIN_THREADS=$(PUMA_MIN_THREADS) \
	PUMA_MAX_THREADS=$(PUMA_MAX_THREADS) \
	PUMA_NUM_WORKERS=$(PUMA_NUM_WORKERS) \
	foreman start

test:
	bundle exec rspec spec
