# Ruby CircleCI 2.x configuration file
#
# Check https://circleci.com/developer/images/image/cimg/ruby for more details
#
version: 2.1

commands:
  bundle-install:
    steps:
      - run:
          name: Install dependencies
          command: |
            gem install bundler
            bundle check || bundle install --retry=3

  build-release:
    steps:
      - run:
          name: Create deploy.json
          command: bundle exec rake login:deploy_json

jobs:
  build:
    docker:
      # Specify the Ruby version you desire here
      - image: cimg/ruby:2.7.2

    steps:
      - checkout
      - bundle-install
      - run:
          name: Run Tests
          command: |
            bundle exec rspec spec

  deploy:
    docker:
      - image: cimg/ruby:2.7.2
    working_directory: ~/identity-fake-server
    parameters:
      space:
        type: string
    steps:
      - checkout
      - bundle-install
      - build-release
      - run:
          name: Install cf cli
          command: |
            curl -v -L -o cf-cli_amd64.deb 'https://cli.run.pivotal.io/stable?release=debian64&source=github'
            sudo dpkg -i cf-cli_amd64.deb
            cf -v

      - run:
          name: login to cloud.gov
          command: |
            cf login -a https://api.fr.cloud.gov -u "14eb6a35-b134-431c-9038-11f44b1337e1" -p $CF_PASS -o "gsa-login-prototyping" -s "<< parameters.space >>"

      - run:
          name: deploy to cloud.gov
          command: |
            bundle config set cache_all true
            bundle package
            cf push identity-fake-server

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: main
          matrix:
            parameters:
              space:
                - pt
